# Generated by Django 6.1 on 2026-08-25 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('storage_key', models.CharField(max_length=300)),
                ('size', models.CharField(choices=[('1024x1024', 'Square 1024 x 1024'), ('1024x1536', 'Portrait 1024 x 1536'), ('1536x1024', 'Landscape 1536 x 1024')], max_length=20)),
                ('quality', models.CharField(choices=[('standard', 'Standard'), ('hd', 'High detail')], max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=120)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='image_user_recent_idx')],
            },
        ),
    ]
