import { screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { ApiError, api } from "../../lib/api";
import * as download from "../../lib/download";
import { makeImage, renderWithProviders } from "../../test/utils";
import { HistoryPage } from "./HistoryPage";

const navigate = vi.fn();

vi.mock("react-router-dom", async () => {
  const actual = await vi.importActual<typeof import("react-router-dom")>("react-router-dom");
  return { ...actual, useNavigate: () => navigate };
});

function page(results: ReturnType<typeof makeImage>[], next: string | null = null) {
  return { count: results.length, next, previous: null, results };
}

beforeEach(() => {
  navigate.mockReset();
  vi.spyOn(api, "restoreSession").mockResolvedValue(null);
});

describe("rendering", () => {
  it("shows a skeleton while loading", () => {
    vi.spyOn(api, "history").mockImplementation(() => new Promise(() => {}));
    renderWithProviders(<HistoryPage />);
    expect(screen.getByRole("status", { name: /loading your history/i })).toBeInTheDocument();
  });

  it("renders a card per image with prompt, size, and thumbnail", async () => {
    vi.spyOn(api, "history").mockResolvedValue(
      page([
        makeImage({ id: 1, prompt: "A futuristic city at sunset" }),
        makeImage({ id: 2, prompt: "A snow leopard", size: "1024x1536" }),
      ]),
    );
    renderWithProviders(<HistoryPage />);

    expect(await screen.findByText("A futuristic city at sunset")).toBeInTheDocument();
    expect(screen.getByText("A snow leopard")).toBeInTheDocument();
    expect(screen.getByText(/1024 x 1536/)).toBeInTheDocument();
    expect(screen.getAllByRole("img")).toHaveLength(2);
  });

  it("lazy loads thumbnails", async () => {
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage()]));
    renderWithProviders(<HistoryPage />);
    const image = await screen.findByRole("img");
    expect(image).toHaveAttribute("loading", "lazy");
  });

  it("gives every thumbnail meaningful alt text", async () => {
    vi.spyOn(api, "history").mockResolvedValue(
      page([makeImage({ prompt: "A copper teapot on linen" })]),
    );
    renderWithProviders(<HistoryPage />);
    expect(
      await screen.findByAltText(/generated image: a copper teapot on linen/i),
    ).toBeInTheDocument();
  });

  it("reports the total count", async () => {
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage(), makeImage({ id: 2 })]));
    renderWithProviders(<HistoryPage />);
    expect(await screen.findByText(/2 images generated by you/i)).toBeInTheDocument();
  });
});

describe("empty state", () => {
  it("explains what to do instead of showing a blank grid", async () => {
    vi.spyOn(api, "history").mockResolvedValue(page([]));
    renderWithProviders(<HistoryPage />);

    expect(await screen.findByText(/no images yet/i)).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: /generate your first image/i }),
    ).toBeInTheDocument();
  });
});

describe("error state", () => {
  it("shows a retry that reloads", async () => {
    const user = userEvent.setup();
    const history = vi
      .spyOn(api, "history")
      .mockRejectedValueOnce(new ApiError(500, "server_error", "Something went wrong on our side."))
      .mockResolvedValueOnce(page([makeImage()]));
    renderWithProviders(<HistoryPage />);

    expect(await screen.findByText(/could not load your history/i)).toBeInTheDocument();
    await user.click(screen.getByRole("button", { name: /try again/i }));

    await screen.findByRole("img");
    expect(history).toHaveBeenCalledTimes(2);
  });
});

describe("delete", () => {
  it("asks for confirmation before deleting", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage({ prompt: "A red balloon" })]));
    const remove = vi.spyOn(api, "remove").mockResolvedValue(undefined);
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /delete this image/i }));

    const dialog = screen.getByRole("dialog", { name: /delete this image\?/i });
    expect(within(dialog).getByText(/cannot be undone/i)).toBeInTheDocument();
    expect(remove).not.toHaveBeenCalled();
  });

  it("removes the card once confirmed", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage({ prompt: "A red balloon" })]));
    const remove = vi.spyOn(api, "remove").mockResolvedValue(undefined);
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /delete this image/i }));
    await user.click(screen.getByRole("button", { name: /delete image/i }));

    await waitFor(() => expect(remove).toHaveBeenCalledWith(42));
    await waitFor(() =>
      expect(screen.queryByText("A red balloon")).not.toBeInTheDocument(),
    );
  });

  it("keeps the image when the user backs out", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage({ prompt: "A red balloon" })]));
    const remove = vi.spyOn(api, "remove").mockResolvedValue(undefined);
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /delete this image/i }));
    await user.click(screen.getByRole("button", { name: /keep it/i }));

    expect(remove).not.toHaveBeenCalled();
    expect(screen.getByText("A red balloon")).toBeInTheDocument();
  });

  it("surfaces a delete failure inside the dialog", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage({ prompt: "A red balloon" })]));
    vi.spyOn(api, "remove").mockRejectedValue(
      new ApiError(500, "server_error", "Something went wrong on our side."),
    );
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /delete this image/i }));
    await user.click(screen.getByRole("button", { name: /delete image/i }));

    const dialog = await screen.findByRole("dialog");
    expect(within(dialog).getByText(/went wrong on our side/i)).toBeInTheDocument();
    expect(screen.getByText("A red balloon")).toBeInTheDocument();
  });
});

describe("download", () => {
  it("downloads with the meaningful filename from the API", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage()]));
    const spy = vi.spyOn(download, "downloadImage").mockResolvedValue(undefined);
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /^download$/i }));

    expect(spy).toHaveBeenCalledWith(
      "http://localhost:8000/media/generated/1/abc.png",
      "chitra-a-futuristic-city-at-sunset-20260825-093000.png",
    );
  });
});

describe("regenerate", () => {
  it("hands the prompt and settings to the generator", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(
      page([makeImage({ prompt: "A copper teapot", size: "1536x1024", quality: "hd" })]),
    );
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /generate again/i }));

    expect(navigate).toHaveBeenCalledWith("/", {
      state: { prompt: "A copper teapot", size: "1536x1024", quality: "hd" },
    });
  });
});

describe("pagination", () => {
  it("appends the next page", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history")
      .mockResolvedValueOnce({
        count: 2,
        next: "http://localhost:8000/api/images/?page=2",
        previous: null,
        results: [makeImage({ id: 1, prompt: "First image" })],
      })
      .mockResolvedValueOnce(page([makeImage({ id: 2, prompt: "Second image" })]));
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /load more/i }));

    expect(await screen.findByText("Second image")).toBeInTheDocument();
    expect(screen.getByText("First image")).toBeInTheDocument();
  });

  it("hides Load more on the last page", async () => {
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage()]));
    renderWithProviders(<HistoryPage />);

    await screen.findByRole("img");
    expect(screen.queryByRole("button", { name: /load more/i })).not.toBeInTheDocument();
  });
});

describe("preview", () => {
  it("opens a full-size dialog", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage({ prompt: "A red balloon" })]));
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /view full size/i }));

    const dialog = await screen.findByRole("dialog", { name: /generated image/i });
    expect(within(dialog).getByText("A red balloon")).toBeInTheDocument();
  });

  it("closes on Escape", async () => {
    const user = userEvent.setup();
    vi.spyOn(api, "history").mockResolvedValue(page([makeImage()]));
    renderWithProviders(<HistoryPage />);

    await user.click(await screen.findByRole("button", { name: /view full size/i }));
    await screen.findByRole("dialog");
    await user.keyboard("{Escape}");

    await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument());
  });
});
