/**
 * PRD 9.8 history gallery: thumbnail preview, full preview, prompt visibility,
 * download, delete with confirmation (FR-10), and regenerate.
 *
 * Deleting is optimistic against a confirmation dialog, never a bare click.
 */

import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import { Alert } from "../../components/ui/Alert";
import { Button } from "../../components/ui/Button";
import { Dialog } from "../../components/ui/Dialog";
import { EmptyState } from "../../components/ui/EmptyState";
import { ImageIcon, SparkIcon, TrashIcon } from "../../components/ui/Icons";
import { Skeleton } from "../../components/ui/Skeleton";
import { useToast } from "../../components/ui/Toast";
import { ApiError, api } from "../../lib/api";
import { truncate } from "../../lib/format";
import { HistoryCard } from "./HistoryCard";
import { ImagePreviewDialog } from "./ImagePreviewDialog";

const PAGE_SIZE = 12;

export function HistoryPage() {
  const navigate = useNavigate();
  const { notify } = useToast();

  const [images, setImages] = useState([]);
  const [count, setCount] = useState(0);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(false);
  const [state, setState] = useState("loading");
  const [loadError, setLoadError] = useState(null);
  const [loadingMore, setLoadingMore] = useState(false);

  const [preview, setPreview] = useState(null);
  const [pendingDelete, setPendingDelete] = useState(null);
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState(null);

  const load = useCallback(async (targetPage, append) => {
    if (append) setLoadingMore(true);
    else setState("loading");
    setLoadError(null);

    try {
      const result = await api.history(targetPage, PAGE_SIZE);
      setImages((current) => (append ? [...current, ...result.results] : result.results));
      setCount(result.count);
      setHasMore(Boolean(result.next));
      setPage(targetPage);
      setState("ready");
    } catch (caught) {
      const message =
        caught instanceof ApiError
          ? caught.message
          : "Could not load your history. Please try again.";
      if (append) {
        notify(message, "info");
      } else {
        setLoadError(message);
        setState("error");
      }
    } finally {
      setLoadingMore(false);
    }
  }, [notify]);

  useEffect(() => {
    void load(1, false);
  }, [load]);

  async function confirmDelete() {
    if (!pendingDelete) return;
    setDeleting(true);
    setDeleteError(null);
    try {
      await api.remove(pendingDelete.id);
      setImages((current) => current.filter((image) => image.id !== pendingDelete.id));
      setCount((current) => Math.max(0, current - 1));
      setPendingDelete(null);
      notify("Image deleted.");
    } catch (caught) {
      setDeleteError(
        caught instanceof ApiError
          ? caught.message
          : "Could not delete that image. Please try again.",
      );
    } finally {
      setDeleting(false);
    }
  }

  function regenerate(image) {
    navigate("/", {
      state: { prompt: image.prompt, size: image.size, quality: image.quality },
    });
  }

  return (
    <>
      <div className="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl text-ink">Generation history</h1>
          <p className="mt-1.5 text-base text-ink-secondary">
            {state === "ready" && count > 0
              ? `${count} image${count === 1 ? "" : "s"} generated by you.`
              : "Every image you generate is saved here."}
          </p>
        </div>
        <Button variant="secondary" onClick={() => navigate("/")} icon={<SparkIcon size={16} />}>
          Generate a new image
        </Button>
      </div>

      {state === "loading" && <HistorySkeleton />}

      {state === "error" && (
        <Alert
          tone="error"
          title="Could not load your history."
          action={
            <Button size="sm" variant="secondary" onClick={() => void load(1, false)}>
              Try again
            </Button>
          }
        >
          {loadError}
        </Alert>
      )}

      {state === "ready" && images.length === 0 && (
        <div className="rounded-xl border border-line bg-surface">
          <EmptyState
            icon={<ImageIcon size={20} />}
            title="No images yet"
            description="Generated images appear here with their prompt, so you can download or regenerate them any time."
            action={
              <Button variant="primary" onClick={() => navigate("/")} icon={<SparkIcon size={16} />}>
                Generate your first image
              </Button>
            }
          />
        </div>
      )}

      {state === "ready" && images.length > 0 && (
        <>
          <ul className="grid list-none grid-cols-1 gap-4 p-0 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {images.map((image) => (
              <li key={image.id}>
                <HistoryCard
                  image={image}
                  onPreview={setPreview}
                  onDelete={setPendingDelete}
                  onRegenerate={regenerate}
                />
              </li>
            ))}
          </ul>

          {hasMore && (
            <div className="mt-6 flex justify-center">
              <Button
                variant="secondary"
                onClick={() => void load(page + 1, true)}
                loading={loadingMore}
                loadingLabel="Loading..."
              >
                Load more
              </Button>
            </div>
          )}
        </>
      )}

      <ImagePreviewDialog image={preview} onClose={() => setPreview(null)} />

      <Dialog
        open={Boolean(pendingDelete)}
        onClose={() => {
          setPendingDelete(null);
          setDeleteError(null);
        }}
        busy={deleting}
        title="Delete this image?"
        description="This permanently removes the image and its prompt from your history. It cannot be undone."
        footer={
          <>
            <Button
              variant="ghost"
              onClick={() => setPendingDelete(null)}
              disabled={deleting}
            >
              Keep it
            </Button>
            <Button
              variant="danger"
              onClick={() => void confirmDelete()}
              loading={deleting}
              loadingLabel="Deleting..."
              icon={<TrashIcon size={16} />}
            >
              Delete image
            </Button>
          </>
        }
      >
        {pendingDelete && (
          <p className="text-sm text-ink-secondary">
            "{truncate(pendingDelete.prompt, 140)}"
          </p>
        )}
        {deleteError && (
          <Alert tone="error" className="mt-3">
            {deleteError}
          </Alert>
        )}
      </Dialog>
    </>
  );
}

function HistorySkeleton() {
  return (
    <div
      className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
      role="status"
      aria-label="Loading your history"
    >
      {Array.from({ length: 8 }).map((_, index) => (
        <div key={index} className="overflow-hidden rounded-xl border border-line bg-surface">
          <Skeleton className="aspect-square w-full" rounded="md" />
          <div className="flex flex-col gap-2 p-3.5">
            <Skeleton className="h-3.5 w-full" />
            <Skeleton className="h-3.5 w-4/5" />
            <Skeleton className="mt-1 h-8 w-32" />
          </div>
        </div>
      ))}
    </div>
  );
}
